package cn.edu.buaa.hzcampus.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*

/** 同一份文档同时服务应用与仓库，避免版本号更新后仍展示旧日志。 */
abstract class SyncUserDocsTask : DefaultTask() {
  @get:Input abstract val appVersion: Property<String>
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val releaseSource: RegularFileProperty
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val guideSource: RegularFileProperty
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val readmeTemplate: RegularFileProperty
  @get:OutputDirectory abstract val kotlinOutput: DirectoryProperty
  @get:OutputFile abstract val readmeOutput: RegularFileProperty
  @get:OutputFile abstract val changelogOutput: RegularFileProperty
  @get:OutputFile abstract val guideOutput: RegularFileProperty

  @TaskAction
  fun sync() {
    val release = releaseSource.get().asFile.readText().replace("\r\n", "\n").trim()
    val guide = guideSource.get().asFile.readText().replace("\r\n", "\n").trim()
    require(release.lineSequence().first() == "v${appVersion.get()}") {
      "请先更新 docs/content/latest-release.txt：首行必须是 v${appVersion.get()}"
    }
    require(Regex("(?m)^v\\d+\\.\\d+\\.\\d+.*$").findAll(release).count() == 1) { "更新日志只能保留最新一个版本" }
    require(guide.isNotBlank()) { "使用说明不能为空" }
    val template = readmeTemplate.get().asFile.readText().replace("\r\n", "\n")
    require(template.contains("{{LATEST_RELEASE}}") && template.contains("{{USAGE_GUIDE}}"))
    fun write(file: java.io.File, content: String) {
      file.parentFile.mkdirs()
      if (!file.exists() || file.readText() != content) file.writeText(content)
    }
    fun quote(value: String): String =
        "\"" +
            value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("\n", "\\n")
                .replace("\r", "\\r") +
            "\""
    write(
        kotlinOutput.file("cn/edu/buaa/hzcampus/ui/screens/menu/UserDocumentation.kt").get().asFile,
        "package cn.edu.buaa.hzcampus.ui.screens.menu\n\n" +
            "// Generated by syncUserDocs. Edit docs/content instead.\n" +
            "internal object UserDocumentation {\n" +
            "  const val changelog = ${quote(release)}\n" +
            "  const val usageGuide = ${quote(guide)}\n}\n",
    )
    val releaseMarkdown = release.replace(Regex("(?m)^· "), "- ")
    val guideMarkdown = guide.replace(Regex("(?m)^(\\d+\\. .+)$"), "### $1\n")
    write(
        readmeOutput.get().asFile,
        template
            .replace("{{LATEST_RELEASE}}", releaseMarkdown)
            .replace("{{USAGE_GUIDE}}", guideMarkdown),
    )
    write(changelogOutput.get().asFile, "# 更新日志\n\n$releaseMarkdown\n")
    write(guideOutput.get().asFile, "# 使用说明\n\n$guideMarkdown\n")
  }
}
